### ISSUE TITLE
add validation to uri format

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/sdk-typescript#101]
**What would you like to be added**:

when running `npm run test`  sdk-typescript it prints out

`unknown format "uri" ignored in schema at path "#/oneOf/0"`

a bunch of times - is there anything in the spec schema we should change to fix this ? maybe its not a problem

**Why is this needed**:

reported by @tsurdilo

**Comment by antmendoza** [comment]
related documentation https://ajv.js.org/guide/formats.html

**Comment by JBBianchi** [comment]
The underlying question is: how do you validate an uri format ? :)

**Comment by antmendoza** [comment]
😅

here there is a "nice" regex https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L51

**Comment by JBBianchi** [comment]
@antmendoza Indeed ^^ we can try `ajv-formats`, it doesn't require a lot of effort. I just wonder why it's not included in the base package and hope it's not creating side effects.
