### ISSUE TITLE
Disclaimer in the README for object literal methodology

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#106]
**What would you like to be added**:
Add a warning in (or completly remove?) the [object literals](https://github.com/serverlessworkflow/sdk-typescript#create-workflow-using-object-literals) section about validation and default values.

**Why is this needed**:
if the developper using the SDK decides to go with the object literals approach, he might face valid objects that don't define default/const values enforced by builders (e.g. #104)

**Comment by antmendoza** [comment]
+1  my preference is to remove it completely
