### ISSUE TITLE
Empty string should be treated as if "no value provided" from the validation point of view 

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/sdk-typescript#107]
**What happened**:

With the actual implementation we are able to build object with properties populated by empty string (without any validation error)

```
{
    "name": "",
    "inputCollection": "",
    "iterationParam": "",
    "workflowId": "",
    "end": true,
    "type": "foreach",
    "usedForCompensation": false
}

```

**What you expected to happen**:

**How to reproduce it**:

The following code should pass, instead is failing 

```
import {foreachstateBuilder} from '../../../src';

describe('xxx', () => {
	
	
	it('xxxxx', () => {
		
		expect(() => foreachstateBuilder()
			.name('')
			.inputCollection('')
			.iterationParam('')
			.workflowId('')
			.end(true)
			.build()).toThrowError();
		
		
	});
});


```

**Anything else we need to know?**:

**Environment**:

**Comment by JBBianchi** [comment]
@antmendoza  It's unfortunatly "a feature, not a bug". `required` just means that the property must exist on the object, it doesn't restrict the value:
```
6.5.3.  required
...
   An object instance is valid against this keyword if every item in the
   array is the name of a property in the instance.
```
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.5.3

I guess we should add a constraint in the schema such as [minLength](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.3.2).

**Comment by antmendoza** [comment]
Hi @JBBianchi it is not unfortunate, it is as it is... thank you. 

I am going to create a pr for the specification.. 

Closing this.
