### ISSUE TITLE
Properties are not serialized in "order"

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/sdk-typescript#130]
**What would you like to be added**:
Would be nice to have a way to define the order in witch are serialized the properties. 

For example, for `eventstate`,   `type` and  `exclusive` properties are always printed in first place:  

```
    "states": [
        {
          "type": "event",
          "exclusive": true,
          "name": "StoreCarAuctionBid",
          "onEvents": [
.....    
]

```
Instead should be: 

```
    "states": [
        {
          "name": "StoreCarAuctionBid",
          "type": "event",
          "exclusive": true,
          "onEvents": [
.....    
]

```

**Why is this needed**:

**Comment by tsurdilo** [comment]
@antmendoza yeah for states please make id(if defined), name ,and type the first three params no matter which state it is

**Comment by tsurdilo** [comment]
@antmendoza also we should define the order of top level properties across all sdks.

some rules that could be applied now:
* id, name, version, description, specversion should go first 
* start property should go right above the states array
* states[] go before functions[] events[], retries[], timeouts ... (and all other reusable definitions)

**Comment by tsurdilo** [comment]
@antmendoza also for things like function definitions, on output we should group them by type, same for events (kinda - produced/consumed). this can be applied to many other definitions (in reusable defs)
