### ISSUE TITLE
NPM package directory structure broke in the 3.0.0 release

### ISSUE THREAD

**Issue by paulovmr** [serverlessworkflow/sdk-typescript#149]
**What happened**:
In the 3.0.0 release artifacts, the `lib` directory is inside a `src` directory, which didn't existed before. This breaks the compilation of typescript files that imported artifacts from this dependency.

2.0.0:
![sdk-typescript_2_0_0](https://user-images.githubusercontent.com/832830/144656794-47361060-975c-45bd-8d0e-440177298661.png)

3.0.0:
![sdk-typescript_3_0_0](https://user-images.githubusercontent.com/832830/144656825-638cefee-0a69-4c73-9935-0b6496f37c61.png)

**What you expected to happen**:
The directory structure in 3.0.0 should be the same as 2.0.0.

**Comment by antmendoza** [comment]
thanks @paulovmr , I will have a look

**Comment by antmendoza** [comment]
still don't know from where this change is coming. Maybe from a transitive dependency. 

I have "fixed" it, will investigate later.

https://github.com/serverlessworkflow/sdk-typescript/pull/150
