### ISSUE TITLE
Typings not present in npm package

### ISSUE THREAD

**Issue by donaldoakes** [serverlessworkflow/sdk-typescript#152]
**What happened**:
File index.d.ts referenced in package.json is missing after install. Causes errors in VS Code due to missing type declarations.

**What you expected to happen**:
Expected index.d.ts to be present in root of installed npm package.

**How to reproduce it**:
`npm i --save @severlessworkflow/sdk-typescript`

**Anything else we need to know?**:

**Environment**:

**Comment by antmendoza** [comment]
Hi @donaldoakes I will look into it

**Comment by antmendoza** [comment]
Hi @donaldoakes it should be working now. Let me know if it does not. 

You can pull the latest version from npm `npm i @severlessworkflow/sdk-typescript@3.0.2`

Thank you!!
