### ISSUE TITLE
Typo in npm organization name

### ISSUE THREAD

**Issue by donaldoakes** [serverlessworkflow/sdk-typescript#155]
**What happened**:
Organization name is `@severlessworkflow`

**What you expected to happen**:
Should be `@serverlessworkflow`

**How to reproduce it**:
`npm i --save @severlessworkflow/sdk-typescript`

**Anything else we need to know?**:
Maybe it's early enough to still change this? Otherwise someone may squat on the proper org name.

**Comment by antmendoza** [comment]
oh shit!! thank you!! still it took me two minutes to see the difference here

**Comment by antmendoza** [comment]
I think we can change for the next release

**Comment by antmendoza** [comment]
fixed #176
