### ISSUE TITLE
No longer available on npmjs?

### ISSUE THREAD

**Issue by hirenr** [serverlessworkflow/sdk-typescript#182]
**What is the question**:

Hi, I am getting a 404 error, when running the command
`npm i @serverlessworkflow/sdk-typescript`

Is something wrong?

**Comment by JBBianchi** [comment]
For some unknown reason, there is a typo in the organisation name -> [@severlessworkflow/sdk-typescript](https://www.npmjs.com/package/@severlessworkflow/sdk-typescript)
