### ISSUE TITLE
Allow browser usage

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#65]
**What would you like to be added**:
Browser usage support. (Either avoid nodejs/browser specific APIs or have two versions if not possible otherwise)

**Why is this needed**:
Allow use on the client-side

Related to #66 
Related to #70

**Comment by antmendoza** [comment]
👍

**Comment by antmendoza** [comment]
@JBBianchi is this one duplicated with #70 ? 

I mean, ones #70 is done this functionality will be supported, isn't it?

**Comment by JBBianchi** [comment]
@antmendoza yes and no, #70 suggests to 'at least add' a method, but indeed a refactor of the existing one will be a huge step in that direction. #66 is also a step as `isYAML` and `isJSON` either need to be removed or to be based on the content rather than the file extension. On the middle/long term, it also means either avoid environement specific APIs or having two versions of the same element adapted to each environement if possible.
