### ISSUE TITLE
Seamlessly parse JSON or YAML using js-yaml

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#66]
**What would you like to be added**:
[BaseWorkflow](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/base-workflow.ts) relies on the provided file extension to either parse the JSON or the YAML. YAML being a superset of JSON, js-yaml is able to parse both seamlessly.

**Why is this needed**:
Removes the need for nodejs fs API (#65) and simplify codebase.

Related to #65 
Related to #70

**Comment by antmendoza** [comment]
👍
