### ISSUE TITLE
Use specific tsconfig for tests

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#67]
**What would you like to be added**:
Use a dedicated `ts.spec.config` and output dir for test.

**Why is this needed**:
You don't want to publish the compiled tests in the final library.

**Comment by antmendoza** [comment]
@JBBianchi the spec folder is excluded (not included) in package.json#files section, so it is not going to be published.

running `npm pack` the spec folder is excluded

Are you ok with it or do you still think that we should have a separate tsconfig file for test?

**Comment by JBBianchi** [comment]
My bad, I didn't pay enough attention. It works indeed and, thb, I have no clue which is the best option of the two. 

A "problem" that comes to my mind when using [package-json#files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) is that it may require maintenance, meaning that, at a point in time, maybe the folder structure changes and you have to remember to update the files array. This might happen if, instead of building/packaging `dist/src`, you decide to provided different versions of the package for different modules systems, for instance `dist/umd` and `dist/esm`. 

I don't want to push any decision, just raise some questions :)

**Comment by antmendoza** [comment]
that is a good point, thank you :)
