### ISSUE TITLE
Avoid circular imports

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#68]
**What would you like to be added**:
Avoid circular imports (imports from index.ts)

**Why is this needed**:
[index.ts](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/index.ts) is the public facing API, meaning it exports modules/classes/functions... other developers may use. It should not be used internally like it's done in some modules such as [action-data-filter.builder.ts](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/model/action-data-filter.builder.ts#L17). They should rely on [types.ts](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/model/types.ts) directly like some other builders do (e.g.: [action.builder.ts](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/model/action.builder.ts#L17)). At some point, it may cause bundling or runtime problems.

**Comment by antmendoza** [comment]
thank you @JBBianchi  I am going to fix it, 

I thing my IDE is changing the imports for me.

**Comment by JBBianchi** [comment]
You're welcome. I don't think it will really be a problem but better safe than sorry :)
