### ISSUE TITLE
BaseWorkflow should parse string, not read a file

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/sdk-typescript#70]
**What would you like to be added**:
[BaseWorkflow.fromSource](https://github.com/serverlessworkflow/sdk-typescript/blob/b46544e35579398c686d245b4d8a5d6856d030f2/src/base-workflow.ts#L24) relies on a path to read a file and then parse its content. This means it requires access to either the nodejs' fs api or browser's file api to access the file's content before parsing it. I think `BaseWorflow` should at least expose a method to parse `Workflow` from a string. 

**Why is this needed**:
Removes the need of file/fs api and provides a more flexible method (the developper can then read the source from an URL, a DB, whatever he fancies)

Related to #66
Related to #65

**Comment by antmendoza** [comment]
agree @JBBianchi , thank you!!
