### ISSUE TITLE
Main readme examples - reading from json/yaml

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/sdk-typescript#85]
**What is the question**:

Is it possible to read json/yaml dsl definition from a file?
Is it possible to read in a variable which defines the json/yaml?

If it is, would be be possible to add that as small example to the main readme?

**Comment by antmendoza** [comment]
Hi @tsurdilo 

> Is it possible to read json/yaml dsl definition from a file?

Depending of the environment (node/browser etc... ) read from file is doing in a different way. see #70 

For node it would be something like 

```
import * as fs from "fs";
... 

const fileAsString = fs.readFileSync(filePath).toLocaleString();` 

const workflow = WorkflowConverter.fromString(fileAsString);
```

we could have different implementations of a `WorkflowSource` (whatever name...) interface in the sdk. Even pack it or not depending of the generated bundle.


> Is it possible to read in a variable which defines the json/yaml?

This is the way , if I am not misunderstanding your question. 
https://github.com/serverlessworkflow/sdk-typescript/blob/main/README.md#load-a-file-jsonyaml-to-a-workflow-instance

I am going to amend the section title, it is confusing. 

> If it is, would be be possible to add that as small example to the main readme?

Sure,

**Comment by antmendoza** [comment]
Hi @tsurdilo I have created a small PR #115 , please let me know if it is clear now
