### ISSUE TITLE
Fix test/examples code

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/sdk-typescript#88]
**What would you like to be added**:

Fix test/examples code to run with the actual code 

**Why is this needed**:

**Comment by JBBianchi** [comment]
I'm working on it. I discovered some problems either in the lib or in the schemas. I'll try to address the issues and open a PR asap.

**Comment by antmendoza** [comment]
Hi @JBBianchi 

me too, 

we are doing double work here

**Comment by antmendoza** [comment]
please @JBBianchi  open issues or ping me on slack so we know in which part we are working and we can coordinate better, 

thank you !! ;)
