### ISSUE TITLE
Unable to "npm link" 

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/sdk-typescript#98]
**What happened**:

Following instructions in main readme:

git clone https://github.com/serverlessworkflow/sdk-typescript.git
cd sdk-typescript
npm install && npm run build
cd dist
npm link

getting this:

<img width="1324" alt="Screen Shot 2021-05-17 at 9 29 13 PM" src="https://user-images.githubusercontent.com/119422/118576728-15c1eb00-b757-11eb-9265-4930198510d9.png">

any help appreciated

**Comment by tsurdilo** [comment]
This worked: 

git clone https://github.com/serverlessworkflow/sdk-typescript.git
cd sdk-typescript
npm install && npm run build
cd dist
touch .git
npm link

**Comment by antmendoza** [comment]
I think that is gonna happen the same with "npm publish"

**Comment by JBBianchi** [comment]
I'll investigate, it looks like a side effect of husky from what I understand.
